### PR TITLE
In screen sharing mode, do not make rows fixed width

### PR DESCRIPTION
**Pull request by karthikv**
To be able to display the 'responsiveness' of the screen components, remove the fixed width assignments so that the user can resize the browser to see that it can adjust accordingly. When exporting functionality is supported, the assumption is that the standalone app will always be a flex width (but something like max-width: 960px, min-width: 320px)

### CODE REVIEW

**Comment by karthikv** [comment]
Actually, there is no responsiveness right now, even if I do remove the fixed width assignments; I haven't yet put in the bootstrap code to include that. We can keep this issue open as an indicator to implement responsiveness in the future.

Also, do you think responsiveness should take precedence over exporting or vice-versa?

**Comment by karthikv** [comment]
@ednapiranha No matter; I just added responsiveness.

**Comment by operatorjen** [comment]
do you need the full twitter bootstrap file if you already included the minified version?

**Comment by karthikv** [comment]
If I need to make changes, it's much easier to edit the uncompressed file and then minify it.

**Comment by karthikv** [comment]
Merged.

**Pull request closed without merging**
