### PR TITLE
Clicking on the trash next to a project deletes it immediately

### PR DESCRIPTION
**Pull request by karthikv**
The trash icon next to a project name deletes it immediately with no way to recover. Wah!

### CODE REVIEW

**Comment by karthikv** [comment]
We're eventually planning to add revisions and/or undo functionality, which should take care of this. I could add in some sort of confirm dialog for now, though. What do you think? Is it important for this first version to have this or should we wait for the more advanced features?

**Comment by operatorjen** [comment]
I'd just put a confirm popup for now :)

**Comment by fwenzel** [comment]
+1. Not as smooth as an undo function, but delete on a project(!) is destructive enough that a confirm popup is the way to go for now.

**Comment by karthikv** [comment]
@ednapiranha Ready for review.

**Pull request merged**
